#!/bin/bash
# =============================================================================
# creative_solver_smoke.sh  –  Train the creative writing solver.
#
# Usage:
#   bash scripts/creative_solver_smoke.sh \
#       <solver_model> <challenger_checkpoint> <Abbreviation> \
#       <num_train> <num_val> <seed>
#
#   solver_model:          HF id or volume path — model being trained (GPUs 0-3).
#   challenger_checkpoint: Merged challenger checkpoint path used to generate
#                          training prompts (e.g. /storage/models/…/huggingface).
#                          Loaded on GPU 7 during Step 0, then released.
#   Abbreviation:          Short name for checkpoint directories.
#
# Training data: prompts generated by the challenger checkpoint via
#   one_shot_creative_question_generate.py, stored as WritingPrompt dicts.
#   Each parquet row: problem = query, answer = WritingPrompt.to_dict() JSON.
#
# Reward (live): solver generates G responses per prompt → BatchEvalAgent scores
#   each → normalised rank reward R_i = (G - rank_i) / (G - 1).
#   G controlled by worker.rollout.n; defaults to SMOKE_SOLVER_ROLLOUT_N (4).
#
# Scale controlled by env (set by train_creative_solver in modal_run.py):
#   SMOKE_SOLVER_MAX_STEPS   (default 4)
#   SMOKE_SOLVER_ROLLOUT_N   (default 4)  — samples per prompt (G)
# =============================================================================

set -euo pipefail

export WANDB_MODE="${WANDB_MODE:-disabled}"
rm -rf /tmp/torchinductor_root /tmp/tinductor_* 2>/dev/null || true

solver_model="$1"
challenger_checkpoint="$2"
Model_abbr="$3"
num_train="${4:-8}"
num_val="${5:-2}"
seed="${6:-42}"

S_STEPS="${SMOKE_SOLVER_MAX_STEPS:-4}"
S_MERGE=$((S_STEPS - 1))
ROLLOUT_N="${SMOKE_SOLVER_ROLLOUT_N:-4}"

# ---------------------------------------------------------------------------
# Run-unique checkpoint name
# ---------------------------------------------------------------------------
# Standalone call: append a fresh timestamp so repeated runs don't collide.
# Called from creative_coevolve_smoke.sh: SMOKE_RUN_ID is exported and
# Model_abbr already contains the run timestamp, so no second stamp is added.
# ---------------------------------------------------------------------------
if [ -z "${SMOKE_RUN_ID:-}" ]; then
    _RUN_TS=$(date +%Y%m%d_%H%M%S)
    SAVE_NAME="${Model_abbr}_solver_v1_${_RUN_TS}"
else
    SAVE_NAME="${Model_abbr}_solver_v1"
fi

# Cap rollout/actor batch sizes to num_train so VERL always has enough data
ROLLOUT_BATCH=$(( num_train < 8 ? num_train : 8 ))
ACTOR_GLOBAL_BATCH=$(( ROLLOUT_BATCH < 8 ? ROLLOUT_BATCH : 8 ))

# Total prompts to generate (train + val)
NUM_PROMPTS=$(( num_train + num_val ))

echo "=========================================================="
echo " Creative Writing Solver Smoke Training"
echo " Solver model        : $solver_model"
echo " Challenger ckpt     : $challenger_checkpoint"
echo " Abbreviation        : $Model_abbr"
echo " Train rows          : $num_train  Val rows: $num_val  Seed: $seed"
echo " Storage             : $STORAGE_PATH"
echo " Max steps           : $S_STEPS  (merge at step $S_MERGE)"
echo " Rollout G           : $ROLLOUT_N  (samples per prompt)"
echo "=========================================================="

# ---------------------------------------------------------------------------
# Pre-flight: verify challenger checkpoint exists before burning any GPU time
# Skip the file-system check for plain HuggingFace model IDs (e.g. Qwen/Qwen3-4B-Base)
# which are downloaded at runtime and have no local config.json yet.
# ---------------------------------------------------------------------------
if [[ "$challenger_checkpoint" == /* ]]; then
    # Absolute local path — must already be a merged HF model directory
    if [ ! -f "${challenger_checkpoint}/config.json" ]; then
        echo "[ERROR] Challenger checkpoint not found: ${challenger_checkpoint}"
        echo "        Expected a merged HuggingFace model directory (containing config.json)."
        echo "        Run creative_challenger_smoke.sh first, or check the path."
        exit 1
    fi
    echo "[OK] Challenger checkpoint verified: $challenger_checkpoint"
else
    echo "[OK] Challenger checkpoint is a HuggingFace model ID (will download at runtime): $challenger_checkpoint"
fi

# ---------------------------------------------------------------------------
# Step 0: Generate training prompts from the challenger checkpoint (GPU 7)
# ---------------------------------------------------------------------------
echo ""
echo ">>> Step 0 — Generating $NUM_PROMPTS prompts from challenger checkpoint"

PROMPTS_SAVE_NAME="${Model_abbr}_solver_prompts"
PROMPTS_SUFFIX="smoke"
PROMPTS_JSON="${STORAGE_PATH}/generated_questions_one_shot/${PROMPTS_SAVE_NAME}_${PROMPTS_SUFFIX}.json"

CUDA_VISIBLE_DEVICES=7 python3 question_generate/one_shot_creative_question_generate.py \
    --model "$challenger_checkpoint" \
    --num_samples "$NUM_PROMPTS" \
    --seed "$seed" \
    --save_name "$PROMPTS_SAVE_NAME" \
    --suffix "$PROMPTS_SUFFIX"

echo "Prompt generation done → $PROMPTS_JSON"

# ---------------------------------------------------------------------------
# Step 1: Build train/val parquet from generated prompts
# ---------------------------------------------------------------------------
echo ""
echo ">>> Step 1 — Building solver train/val parquet"

python3 - <<PYEOF
import sys, os, json
sys.path.insert(0, os.environ.get("REMOTE_REPO_PATH", "/root/R-Zero"))

from pathlib import Path
import pandas as pd
from question_generate.one_shot_creative_question_generate import WritingPrompt

_iteration          = int(os.environ.get("COEVOLVE_ITERATION", "1"))
_run_id             = os.environ.get("SMOKE_RUN_ID", "standalone")
_challenger_ckpt    = "$challenger_checkpoint"

prompts_json = "${PROMPTS_JSON}"
out_dir      = Path("${STORAGE_PATH}/creative_smoke")
out_dir.mkdir(parents=True, exist_ok=True)

with open(prompts_json) as f:
    data = json.load(f)

raw_prompts = data.get("prompts", [])

# Validate and deserialise — only rows with a non-empty query and at least
# one evaluation criterion are kept.  Bad rows are logged and skipped here
# so the reward function can trust the parquet unconditionally.
valid, skipped = [], 0
for p in raw_prompts:
    try:
        wp = WritingPrompt.from_dict(p)
        assert wp.query.strip(),  f"empty query  in {wp.prompt_id}"
        assert wp.criteria,       f"no criteria  in {wp.prompt_id}"
        valid.append(wp)
    except Exception as e:
        print(f"  [skip] {e}")
        skipped += 1

print(f"  Valid prompts: {len(valid)}  Skipped: {skipped}")

num_train = int("${num_train}")
num_val   = int("${num_val}")
assert len(valid) >= num_train + num_val, (
    f"Need {num_train + num_val} valid prompts, got {len(valid)}"
)

train_prompts = valid[:num_train]
val_prompts   = valid[num_train : num_train + num_val]

def make_row(wp: WritingPrompt) -> dict:
    req = wp.requirements.to_dict() if wp.requirements else {}
    return {
        # VERL required — answer holds the full WritingPrompt JSON so the
        # reward function (creative_solver_caller.py) can reconstruct the
        # prompt_id, query, and criteria without a separate lookup.
        "problem":                  wp.query,
        "answer":                   json.dumps(wp.to_dict()),
        # WritingPrompt fields as queryable columns (no JSON parsing needed)
        "prompt_id":                wp.prompt_id,
        "domain":                   wp.domain,
        "domain_name":              wp.domain_name,
        "subdomain":                wp.subdomain,
        "num_criteria":             len(wp.criteria),
        "criteria_json":            json.dumps(wp.criteria),
        "requirements_style":       req.get("style") or "",
        "requirements_format":      req.get("format") or "",
        "requirements_length":      req.get("length") or "",
        "guidance_applied_json":    json.dumps(wp.guidance_applied),
        "num_guidance_applied":     len(wp.guidance_applied),
        "format_score":             wp.format_score,
        "language":                 wp.language,
        "seed":                     wp.seed,
        # run provenance
        "iteration":                _iteration,
        "run_id":                   _run_id,
        "challenger_checkpoint":    _challenger_ckpt,
    }

train_path = out_dir / "${Model_abbr}_solver_train.parquet"
val_path   = out_dir / "${Model_abbr}_solver_val.parquet"

pd.DataFrame([make_row(wp) for wp in train_prompts]).to_parquet(train_path, index=False)
pd.DataFrame([make_row(wp) for wp in val_prompts]).to_parquet(val_path,   index=False)

cols = list(pd.DataFrame([make_row(train_prompts[0])]).columns)
print(f"  [OK] train={len(train_prompts)}  val={len(val_prompts)}  iter={_iteration}  run={_run_id}")
print(f"       columns ({len(cols)}): {cols}")
print(f"       -> {out_dir}")
PYEOF

echo "Parquet build done."

# ---------------------------------------------------------------------------
# Step 2: Train solver with VERL GRPO + normalised rank reward
# ---------------------------------------------------------------------------
echo ""
echo ">>> Step 2 — Training solver ($solver_model, $S_STEPS steps, G=$ROLLOUT_N)"

TRAIN_PARQUET="${STORAGE_PATH}/creative_smoke/${Model_abbr}_solver_train.parquet"
VAL_PARQUET="${STORAGE_PATH}/creative_smoke/${Model_abbr}_solver_val.parquet"

CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m verl.trainer.main \
    config=examples/config.yaml \
    data.train_files="$TRAIN_PARQUET" \
    data.val_files="$VAL_PARQUET" \
    data.prompt_key=problem \
    data.answer_key=answer \
    data.max_prompt_length=2048 \
    data.max_response_length=4096 \
    data.rollout_batch_size="$ROLLOUT_BATCH" \
    data.val_batch_size="$num_val" \
    worker.actor.model.model_path="$solver_model" \
    trainer.experiment_name="$SAVE_NAME" \
    trainer.save_checkpoint_path="${STORAGE_PATH}/models/${SAVE_NAME}" \
    trainer.total_epochs=1000 \
    worker.reward.reward_function=./examples/reward_function/creative_solver_caller.py:compute_score \
    trainer.val_freq=-1 \
    trainer.n_gpus_per_node=4 \
    worker.rollout.n="$ROLLOUT_N" \
    worker.rollout.enforce_eager=true \
    worker.actor.use_torch_compile=false \
    worker.actor.global_batch_size="$ACTOR_GLOBAL_BATCH" \
    worker.actor.micro_batch_size_per_device_for_update=1 \
    worker.actor.micro_batch_size_per_device_for_experience=1 \
    trainer.max_steps="$S_STEPS" \
    trainer.save_freq=1 \
    trainer.project_name="r-zero-creative" \
    trainer.logger='[console,wandb]'

echo "Solver training done — merging checkpoint at global_step_${S_MERGE}"
sleep 5

# ---------------------------------------------------------------------------
# Step 3: Merge checkpoint
# ---------------------------------------------------------------------------
python scripts/model_merger.py \
    --local_dir "${STORAGE_PATH}/models/${SAVE_NAME}/global_step_${S_MERGE}/actor"

echo "Checkpoint merged."

echo ""
echo "=========================================================="
echo " Creative Solver Smoke Training Complete"
echo " Checkpoint: ${STORAGE_PATH}/models/${SAVE_NAME}/"
echo "=========================================================="
